# Generated by Django 4.2.6 on 2023-10-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FertilizerPredictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='chart_type',
            field=models.CharField(choices=[('bar', 'bar'), ('line', 'line'), ('pie', 'pie')], default='BAR', max_length=10),
        ),
    ]
