# Generated by Django 4.2.6 on 2023-11-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FertilizerPredictor', '0003_alter_data_chart_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='chart_type',
            field=models.CharField(default='bar', max_length=20),
        ),
    ]
